"""number

Revision ID: a6e28e24f676
Revises: 4c19a950a4f7
Create Date: 2025-09-04 18:30:28.769763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6e28e24f676'
down_revision: Union[str, Sequence[str], None] = '4c19a950a4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('tg_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('activity_logs_user_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_column('activity_logs', 'user_id')
    op.add_column('notifications', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_column('notifications', 'user_id')
    op.add_column('payments', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.add_column('payments', sa.Column('number_of_months', sa.Integer(), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=28),
               existing_nullable=True)
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_column('payments', 'user_id')
    op.add_column('peers', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('peers_user_id_fkey'), 'peers', type_='foreignkey')
    op.create_foreign_key(None, 'peers', 'users', ['tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_column('peers', 'update_at')
    op.drop_column('peers', 'user_id')
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('peers', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('peers', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'peers', type_='foreignkey')
    op.create_foreign_key(op.f('peers_user_id_fkey'), 'peers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('peers', 'tg_id')
    op.add_column('payments', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=28),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('payments', 'number_of_months')
    op.drop_column('payments', 'tg_id')
    op.add_column('notifications', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'tg_id')
    op.add_column('activity_logs', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_user_id_fkey'), 'activity_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activity_logs', 'tg_id')
    # ### end Alembic commands ###
